### PR TITLE
fix: 🐛 allow extraction of template strings with ", ' and ) in the key

### LINKED ISSUE #87: Keys with ', " or ) are not extracted from HTML
### Current behavior
Keys with the characters `'`, `"` or `)` are not extracted from HTML. The same works with `translate()` in JS code.
Example:
```html
<h2>{{ t("Height (m)") }}</h2>
```

### Expected behavior
They are extracted.

### Steps To Reproduce
Run the extractor on the HTML snippet above.

### Contribution
I will open a PR to discuss a potential fix.

### PR DESCRIPTION
**Pull request by rhuitl**
This should fix #87.

I wonder if I'm making the regex too loose, but I'm confident as it is using greedy matching and it works on a larger project of mine, as well as the tests pass.

### CODE REVIEW

**Comment by shaharkazaz** [comment]
@rhuitl Thanks for the PR.
I'm trying to better understand your translation keys convention.
Although you can use keys with these chars why would you?
In the provided example why not use: `Height (m)` -> `height-m` or `height-meter`

Can you please add tests for the new use case you are covering? 🙂

**Comment by rhuitl** [comment]
Our application is using both AngularJS and Angular. We are using angular-gettext (https://angular-gettext.rocketeer.be/) for the old parts, so all our HTML and gettext calls in code use the English text instead of keys.

When we introduced Angular and decided to use Transloco, we kept doing it this way, and it is working pretty well. It has a few advantages:
* no need to invent key names / standardize a naming convention for the keys
* existing translations will be reused automatically (no need to know how you have to name the key for an "OK" button)
* you can send out a single json file to translators and they'd have the English text right next to where they'd have to type the translation

I guess these are minor points and we are actually considering to switch to using keys instead. It just seems to add an extra step of work as compared to a gettext-like workflow, without providing a whole lot of advantages.

I'll take a look at your test suite.

**Comment by shaharkazaz** [comment]
@rhuitl any update on that? 🙂

**Comment by rhuitl** [comment]
Hi @shaharkazaz I was trying to add this to your test suite, but didn't get very far because it seems like the existing tests rely on having numbers as keys (the `gKeys` method), so I was not able to simply add a non-numeric key to the existing files. Can you provide some ideas how to test this?

**Comment by evanfuture** [comment]
Just to comment on this, we're prevented from migrating ahead because of this behaviour.  We're following the gettext standard for sending translations to poedit, and from all we've read, you're supposed to use the string as the key.  Meaning, if you have `Bob's Burgers`, we'd pass in `t('Bob\'s Burgers')`.  But because of this regex, the key ends up being `Bob`.

So, either this fix or something that allows escaped characters would be really nice to have.

**Comment by rhuitl** [comment]
@evanfuture you could use git+https://github.com/rhuitl/transloco-keys-manager.git#mine-dist for the time being.

**Comment by shaharkazaz** [comment]
@rhuitl You can add manually test for keys that are not numbers, you can see examples in the existing tests 🙂

**Comment by shaharkazaz** [comment]
@evanfuture if this is your blocker, why not just use: `t("Bob's Burgers")`? 🙂

**Comment by evanfuture** [comment]
Well, it gets more complicated.  eg, `[innerHTML]="t('Congratulations! You\'ve completed everything that\'s available to you. Click the #!completed# tab to revisit older items') | replaceTemplate:'#!completed#':t1"` where t1 is an ng-template that the replaceTemplate pipe plops into place.  I can also move that whole string into the component, and then use a marker to be sure it's found when extracting.  Just, well, that's a bit much to ask the team to remember to do when things get complicated.

**Comment by shaharkazaz** [comment]
@evanfuture Thanks for clarifying with an example 👍 
Once tests are added I'll merge this PR

**Comment by shaharkazaz** [comment]
Fixed in v3

**Comment by evanfuture** [comment]
@shaharkazaz that's excellent, it works really well for most use-cases.  I notice, however that it still fails when the translate function is followed by a pipe, eg, `{{t('another(test)' | json)}}`.  Should I open an issue for this?

**Pull request closed without merging**
