### PR TITLE
fix: extractKeys could not find any files with backslashes

### PR DESCRIPTION
**Pull request by JelleBruisten**
this change makes it so every backslash is replaced with a slash like on unix/linux systems. glob on window system did not output any files with backslashes with this change it makes sure that the file path is as expected

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
When having a file directory as input to the extractKeys like `'E:/Frontend/libs/booking/feature-booking-actions/src/lib/`

The glob would result in no files being found :(

```
- Extracting Template and Component Keys � test
√ Extracting Template and Component Keys �
ℹ 0 keys were found in 0 file.
```

Issue Number: N/A

## What is the new behavior?
With changing the backslashes before putting it into the glob.sync, we start to find the correct files again :D
```
√ Extracting Template and Component Keys �
ℹ 226 keys were found in 89 files.
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Comment by JelleBruisten** [comment]
@shaharkazaz I accidentally closed the previous pr, but I did some quick testing and the issue is not resolved with `path.resolve` you know of a way such that windows paths be converted to unix paths? such that glob will list the correct files?

`E:\foo\bar\baz` which does not result in any results from glob.sync

while we would need to convert it to `E:/foo/bar/baz` for it to give correct results

**Comment by JelleBruisten** [comment]
Another option I have found is to pass in 

`{  windowsPathsNoEscape: true } ` to the glob from their repo:

Note Glob patterns should always use / as a path separator, even on Windows systems, as \ is used to escape glob characters. If you wish to use \ as a path separator instead of using it as an escape character on Windows platforms, you may set windowsPathsNoEscape:true in the options. In this mode, special glob characters cannot be escaped, making it impossible to match a literal * ? and so on in filenames.

**Comment by shaharkazaz** [comment]
@JelleBruisten I'm not sure about this flag, seems like it's bringing back a buggy behavior according to the docs.
A couple of notes:
1. Create a function that uses the glob search but normalizes the paths from back slashes to forward slashes.
2. Search and use it in all the glob usages

**Comment by JelleBruisten** [comment]
It's either that or the previous replace since according to the docs we need to either replace or use that config option. Since resolve will output `\` on Windows which would be used as a escape character by glob, so we either replace `/` by `\\` or `/`.

**Comment by JelleBruisten** [comment]
I Updated the PR so it has the previous solution, with a replace so it does replace `\` with `\\` such that `\` is getting escaped correctly

**Comment by shaharkazaz** [comment]
@JelleBruisten As I said, please move this to a new function which normalizes the path and executes glob.sync.
There are more places that use glob and we need to handle all of them.

**Comment by shaharkazaz** [comment]
@JelleBruisten Nice, please merge master, you have conflicts.

**Comment by JelleBruisten** [comment]
@shaharkazaz should be resolved now

**Pull request merged**
