### PR TITLE
Handle expressions with pipes

### PR DESCRIPTION
**Pull request by AbdealiJK**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Expressions with pipes were not handled
Issue Number: https://github.com/ngneat/transloco-keys-manager/issues/129

## What is the new behavior?
We handle expressions with pipes

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by shaharkazaz — COMMENTED** [review]
Looking good, please add these test cases:
1. Expressions that aren't strings
2. Expressions where the right side is the transloco call

**Comment by AbdealiJK** [comment]
1. You want me to add something like `1 + 2` ? That won't have any translation keys to extract right ?
2. Got it

**Comment by shaharkazaz** [comment]
@AbdealiJK Correct and also:
`(.. | transloco) + varFromComp` &  `(.. | transloco) + 12`, some variations around that just so we'd have coverage and make sure it's working as expected.

**Comment by AbdealiJK** [comment]
@shaharkazaz Added some more tests. Also found that the condition part in `condition ? left : right` could also have translations that we were not handling while adding the testcase. So, added that too

**Review by shaharkazaz — APPROVED** [review]
Great job 👍 
I'm glad to see that the refactor in v3 allows us to do these kind of fixes quickly

**Pull request merged**
