### PR TITLE
feat: 🎸 Add support for angular 16-17

### PR DESCRIPTION
**Pull request by kekel87**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The library does not work with templates containing self-closing (Angular 15) components and control flows (Angular 17).

Issue Number: #171, #155 

## What is the new behavior?

It works.
Self-closing components work without changing anything other than updating the compiler.
I added processing to pass through Control Flows (`BlockNode`).
It's really not something I've mastered, I did the best I could. 😅 

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

🤷 Perhaps old versions of Angular that are no longer supported via the latest compiler.

## Other information
- update `@angular/compiler` to latest `17.0.9` to support new stuff
- update `jest` and `@types/jest` and add `jest-preset-angular` to support new angular compiler version
- update jest config to works with angular compiler 
- fix typing issues
- spy console.log in specific test
- fix regression on pipe extractor (translation `77`) with `isPropertyRead`
- implement function to detect `BlockNode` and get children of `BlockNode`
- add unit test to self-closing tag and control flow

### CODE REVIEW

**Comment by shaharkazaz** [comment]
Thanks for the PR 🥳 
See that the CI is failing.
Have you tested these changes on a fresh project? it's been a while since I've worked on the upgrade but I remember having issues with the fact that the compiler is now ESM.
I have a branch with a lot of core changes in it, I'll try to push it forward as I see you encountered some of the issues I had.

**Comment by kekel87** [comment]
Hi, sorry I wasn't available this week.
I think it's going to be good.

**Comment by shaharkazaz** [comment]
@kekel87 

> Have you tested these changes on a fresh project?

**Comment by kekel87** [comment]
@shaharkazaz You're right, it doesn't work, sorry.

I'm going to take your migration to ESM that you started on your branch.
It's not something I've mastered very well, but I'll try to do my best, in parallel with my work.

**Comment by shaharkazaz** [comment]
@kekel87 I'm closing this PR, I'll hopefully finish my work as most of it is done and you can take it from there.
Wait for my merge to master so we don't double work.

**Pull request closed without merging**
